version: '1.0'

services:
  database:
    image: gleisonfreitas/meu-bd:1.1
    container_name: metadex-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - metadex_db_data:/var/lib/mysql
    networks:
      - metadex-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pMeta2309"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-java:
    image: gleisonfreitas/meu-java:2.2
    container_name: metadex-backend
    restart: always
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=metadex
      - DB_USER=admin_metadex
      - DB_PASSWORD=Meta2309
    depends_on:
      database:
        condition: service_healthy
    networks:
      - metadex-network

  frontend-site:
    image: gleisonfreitas/meu-site:v1.0
    container_name: metadex-site
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=metadex
      - DB_USER=admin_metadex
      - DB_PASSWORD=Meta2309
    depends_on:
      database:
        condition: service_healthy
    networks:
      - metadex-network

# Configurações de Rede e Persistência
networks:
  metadex-network:
    driver: bridge

volumes:
  metadex_db_data:
    driver: local