version: '3.8'

services:
  database:
    image: gleisonfreitas/meu-bd:1.3
    container_name: metadex-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - metadex_db_data:/var/lib/mysql
    networks:
      - metadex-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-P", "3306", "--protocol=tcp", "-u", "admin_metadex", "-pMeta2309"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  s3-pseudoetl-service:
    image: gleisonfreitas/meu-java:3.0
    container_name: metadex-java
    restart: "no"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=metadex
      - DB_USER=admin_metadex
      - DB_PASSWORD=Meta2309
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=contato.metadex@gmail.com
      - SMTP_PASSWORD=afgsffbuzhqpcveo
    depends_on:
      database:
        condition: service_healthy
    networks:
      - metadex-network

  java-mail:
    image: gleisonfreitas/meu-javamail:2.0
    container_name: metadex-javamail
    restart: "no"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=metadex
      - DB_USER=admin_metadex
      - DB_PASSWORD=Meta2309
    depends_on:
      database:
        condition: service_healthy
    networks:
      - metadex-network

  frontend-site:
    image: gleisonfreitas/meu-site:v1.0
    container_name: metadex-site
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=metadex
      - DB_USER=admin_metadex
      - DB_PASSWORD=Meta2309
    depends_on:
      database:
        condition: service_healthy
    networks:
      - metadex-network

# Configurações de Rede e Persistência
networks:
  metadex-network:
    driver: bridge

volumes:
  metadex_db_data:
    driver: local